// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package products

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ProductList struct {
	_tab flatbuffers.Table
}

func GetRootAsProductList(buf []byte, offset flatbuffers.UOffsetT) *ProductList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ProductList{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsProductList(buf []byte, offset flatbuffers.UOffsetT) *ProductList {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ProductList{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ProductList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ProductList) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ProductList) Products(obj *Product, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ProductList) ProductsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ProductListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ProductListAddProducts(builder *flatbuffers.Builder, products flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(products), 0)
}
func ProductListStartProductsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ProductListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
